# S'nce Group basic Docker composer for PHP/Symfony projects

version: "3.2"
services:

    redis:
      image: redis:alpine
      container_name: snce-docker-redis
      ports:
        - "6379:6379"

    mysql:
      image: mysql:5.7
      container_name: snce-docker-mysql
      volumes:
        - ./mysql-data:/var/lib/mysql:cached
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=project-db
        - MYSQL_USER=project-db
        - MYSQL_PASSWORD=project-db
      ports:
        - "3306:3306"

    webserver:
      image: nginx:alpine
      container_name: snce-docker-webserver
      working_dir: /application
      environment:
          - SYMFONY_ENV
      volumes:
          - .:/application:cached
          - ./docker-config/nginx/nginx_${SYMFONY_ENV}.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8080:80"
      links:
       - php-fpm

    php-fpm:
      build:
        context: .
        dockerfile: docker-config/php-fpm/Dockerfile
      container_name: snce-docker-php-fpm
      working_dir: /application
      environment:
          - SYMFONY_ENV
      volumes:
        - .:/application:cached
        - ./docker-config/php-fpm/php-ini-overrides_${SYMFONY_ENV}.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini

      links:
        - mysql
        - redis
